<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books  [
<!ELEMENT  books (book*)>
<!ELEMENT book  (bookid,bookname,price,author)>
<!ELEMENT bookid  (#PCDATA)>
<!ELEMENT bookname  (#PCDATA)>
<!ELEMENT price  (#PCDATA)>
<!ELEMENT author  (#PCDATA)>
]>
<books>
<book>
<bookid> 34</bookid>
<bookname> the  dare</bookname>
<price> 20.90</price>
<author> lucky</author>
</book>

<book>
<bookid> 94</bookid>
<bookname> jjava</bookname>
<price> 22</price>
<author> venky</author>
</book>
</books>