<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books  [
<!ELEMENT  books (book*)>
<! ELEMENT book (bookid,price,author,publisher)>
<!ELEMENT bookid (#PCDATA)>
<!ELEMENT bookname (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT author (#PCDATA)>
]>
<books>
<book>
<bookid>34</bookid>
<bookname>the dare</bookname>
<price>20.90</price>
<author>sri</author>
</book>

<book>
<bookid>94</bookid>
<bookname>tpatente</bookname>
<price>22</price>
<author>srividya</author>
</book>
</books>